sudo: required
dist: trusty
language: node_js
node_js:
- '6'
env:
  matrix:
  - NODE_ENV=TEST
  global:
    secure: htXQrMDUt8baBoECLuag1v7f72GpZDYkdpXiy2xq0O4ohXaCMFYKJVBc+m67uBQTm+cy1MCusKwKumDJyJ8JnSTM9Lo8oB6nKavqSfDVdqOe9DJSCIOkwYePPAyvim80vLcH1/sPQ52B8mdB1TWM7kpG5wzryT0QyamtUcn2TIWyOPmoiu/WA7zKKhs4hFV9JAf8aoTQKMooDZ3mIVY2wYm/3OkrbUc0J1zYQdTx5K8hKcD+1+PcYZOGshW5gBeuXf2M8p0Us/R4DREBivg3GlBd6BX0/cFpntRXDW4dtt2mD6CJ972nZgwDJBAA01fFVCXES6COdWmIQ0z3+/4VgA63t0QeK8EGkww6fse+llviW8hcMRtgsQAexuFdPHHm7jpkzo1WFslHc3AvZAcNksYERvKsITMp07tT45lCwXAhplaVfsLbNMoLaQaPRJKolGbbY7CRod1hUWXzwhxiL/D4918Hb+O2eyQsDIMyybMBpv0NrMh9c3lOuv9dQov5f1kt0CASIFfdN1sus/pjnwXoQmWrSvHBfNoesZDCwqpO6gWwUIVHOjdxXWGhAYir49lp9r0BbfIPk02eV/EeRrQVGcgwkh4gr/mAqEwtboyF6QZEFzQoRDhDH7bzyg8lVPdAit0mjAlJxDn/A+MjEJuhyPyTMyU2cpd6hmHcI/s=
addons:
  sonarqube:
    organisation: idriss92
    token:
      secure: htXQrMDUt8baBoECLuag1v7f72GpZDYkdpXiy2xq0O4ohXaCMFYKJVBc+m67uBQTm+cy1MCusKwKumDJyJ8JnSTM9Lo8oB6nKavqSfDVdqOe9DJSCIOkwYePPAyvim80vLcH1/sPQ52B8mdB1TWM7kpG5wzryT0QyamtUcn2TIWyOPmoiu/WA7zKKhs4hFV9JAf8aoTQKMooDZ3mIVY2wYm/3OkrbUc0J1zYQdTx5K8hKcD+1+PcYZOGshW5gBeuXf2M8p0Us/R4DREBivg3GlBd6BX0/cFpntRXDW4dtt2mD6CJ972nZgwDJBAA01fFVCXES6COdWmIQ0z3+/4VgA63t0QeK8EGkww6fse+llviW8hcMRtgsQAexuFdPHHm7jpkzo1WFslHc3AvZAcNksYERvKsITMp07tT45lCwXAhplaVfsLbNMoLaQaPRJKolGbbY7CRod1hUWXzwhxiL/D4918Hb+O2eyQsDIMyybMBpv0NrMh9c3lOuv9dQov5f1kt0CASIFfdN1sus/pjnwXoQmWrSvHBfNoesZDCwqpO6gWwUIVHOjdxXWGhAYir49lp9r0BbfIPk02eV/EeRrQVGcgwkh4gr/mAqEwtboyF6QZEFzQoRDhDH7bzyg8lVPdAit0mjAlJxDn/A+MjEJuhyPyTMyU2cpd6hmHcI/s=
    github_token:
      secure: Vl5WFftBaKrLkXVyRMMrdMJIbqEvs82wjWeH3K0PEzVVpp4sXdN866BdZUbThgpmJ2iKkKjDb8uaEfoDhpQBqF/px5yqvkIA7sMYxLHLrrDie+grZo4c4Xy0QOVlDzbq77zJoyzAzDX+MVjfkI7tIyQPKRUFtYjRQYVaxIw+T9Wb5las9GHzNZcVD0LLg/jc/K1AfsljuKy774QlNlEYyXalSRTh4DfDSKJTj52CNzOuTa27woGT8RmAiXBMQGy0S8WD35Jyl9ynb3IZ2ls9NycRt+ptilFtFLZJ7moqvrrZpTMkeSp5hIvil2TeIbtC9PuY9c+DWOZmIc6m5JLJ2y8s2U9i6TAxwDKBQcY8TizCwmUlIjrr/abXUBi3+TZSSFBATyvuOI4vsTEwZeExYtvKyraLCTxOZs8uNvL/1yoRe92brcjfWes/SPcJobBrLozMOcididSS/OD13DdCOtBy9DC2fya8djSaGaS58y3xJ5B+omQ8s+PopMjKM9mgSeKpeUhS7yEWSRD4Dsb+Zf+dz6ufmLyG0WSGLua9ftFds0MqZ67yaqzHmi3PVn1qxKulWhaI9x67xabnBE5hYCUpdb1zK0NhZ12ckHhYOAUAAUtkVqpSNsr2nUOJZlflHINb37T+xFgKvLgVdXHU/+oPpB/kr2XT1itYN2n9Reg=
  branches:
  - master
script:
- sonar-scanner
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.sonar/cache"
notifications:
  email: false
