sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

env:
  - NODE_ENV=TEST

addons:
  sonarqube:
    organisation: "idriss92"
    token:
      secure: HP2u4WlUm4UMOsUK/QO3/bXo7sznCGZboc3YEOMpbTkx7bu34vG1ZFTh0uDVLeD/Pjhhe0ogAIiyNJCq9UQr2BcokSSYYE9T0gbCNUp+1rUu2hne/6ueJdpl6WWaw8fFGPXz8pz6meFrHXX9VnDGZfXYHknXAZd03RHMN30n4RSCwM53VkLWd783vA2ygORuEQz2w+ZhXXVD0sNVH1Uh2kPwDuCjOjXqag1KHgyu6DpC1sI3yMolgQMMM7dWt0bcCpex02YSW24ETthkaP/dk66Wp2BPkgtVCA7YaTvJPjGTy22OqJLQVxGTxQoL8X40b03HeNjXdw2BDR3Bfmvj7CFb96kIDDcefiB2r5I5HmGMwAzGcdYMpTmR8Ss0U2UYhCTectMme2OAfcWhp8O8KUaeeDt4hHybawIKTx2xWFi46ulh+xzSDyyd830iBkal7Bp7RmEzvHFGHY3yV0lbjcwl8WQj1dfY3rQLv8FgBOXjALFECeDDQLwDlLyNcS1Gzj/FNj1k4YP7NHe4NrJS28uoayiytJX5eD/ieB+YEXKvkUjQ+X57S9vjqTta5Z2ThuTZHdzB64oSY8DjB82Rjuvq/mEaP/ZgVhNPuvC3maZyI0L8MGjtMs11EWhVPaRu8i5Ngp+zXC7dbshgA5N1cqzY0vYbQzXk9f3ZJ0nlCMQ=
    github_token:
      secure: Vl5WFftBaKrLkXVyRMMrdMJIbqEvs82wjWeH3K0PEzVVpp4sXdN866BdZUbThgpmJ2iKkKjDb8uaEfoDhpQBqF/px5yqvkIA7sMYxLHLrrDie+grZo4c4Xy0QOVlDzbq77zJoyzAzDX+MVjfkI7tIyQPKRUFtYjRQYVaxIw+T9Wb5las9GHzNZcVD0LLg/jc/K1AfsljuKy774QlNlEYyXalSRTh4DfDSKJTj52CNzOuTa27woGT8RmAiXBMQGy0S8WD35Jyl9ynb3IZ2ls9NycRt+ptilFtFLZJ7moqvrrZpTMkeSp5hIvil2TeIbtC9PuY9c+DWOZmIc6m5JLJ2y8s2U9i6TAxwDKBQcY8TizCwmUlIjrr/abXUBi3+TZSSFBATyvuOI4vsTEwZeExYtvKyraLCTxOZs8uNvL/1yoRe92brcjfWes/SPcJobBrLozMOcididSS/OD13DdCOtBy9DC2fya8djSaGaS58y3xJ5B+omQ8s+PopMjKM9mgSeKpeUhS7yEWSRD4Dsb+Zf+dz6ufmLyG0WSGLua9ftFds0MqZ67yaqzHmi3PVn1qxKulWhaI9x67xabnBE5hYCUpdb1zK0NhZ12ckHhYOAUAAUtkVqpSNsr2nUOJZlflHINb37T+xFgKvLgVdXHU/+oPpB/kr2XT1itYN2n9Reg=
  branches:
    - master

script:
  - sonar-scanner

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false