environment:
  matrix:
  - nodejs_version: 6
  - nodejs_version: 7

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install yarn && set PATH=%APPDATA%\yarn;%PATH%
  - npm -g install istanbul && set PATH=%APPDATA%\istanbul;%PATH%
  - yarn install

test_script:
  - node --version
  - yarn --version
  # - yarn run test

build: off