// TOURNAMENT LIST
export const FETCH_TOURNAMENTS = "FETCH_TOURNAMENTS"
export const FETCH_TOURNAMENTS_SUCCESS = "FETCH_TOURNAMENTS_SUCCESS"
export const FETCH_TOURNAMENTS_FAILURE = "FETCH_TOURNAMENTS_FAILURE"
export const RESET_ACTIVE_TOURNAMENT = "RESET_ACTIVE_TOURNAMENT"

// CREATE NEW TOURNAMENT
export const CREATE_TOURNAMENT = "CREATE_TOURNAMENT"
export const CREATE_TOURNAMENT_SUCCESS = "CREATE_TOURNAMENT_SUCCESS"
export const CREATE_TOURNAMENT_FAILURE = "CREATE_TOURNAMENT_FAILURE"
export const NEW_TOURNAMENT_RESET = "NEW_TOURNAMENT_RESET"

// VALIDATE TOURNAMENT LIST
export const VALIDATE_TOURNAMENT_FIELDS = 'VALIDATE_TOURNAMENT_FIELDS';
export const VALIDATE_TOURNAMENT_FIELDS_SUCCESS = 'VALIDATE_TOURNAMENT_FIELDS_SUCCESS';
export const VALIDATE_TOURNAMENT_FIELDS_FAILURE = 'VALIDATE_TOURNAMENT_FIELDS_FAILURE';
export const RESET_TOURNAMENT_FIELDS = 'RESET_TOURNAMENT_FIELDS';


// DELETE TOURNAMENT
export const DELETE_TOURNAMENTS = "DELETE_TOURNAMENTS"
export const DELETE_TOURNAMENTS_SUCCESS = "DELETE_TOURNAMENTS_SUCCESS"
export const DELETE_TOURNAMENTS_FAILURE = "DELETE_TOURNAMENTS_FAILURE"
export const RESET_DELETED_TOURNAMENT = "RESET_DELETED_TOURNAMENT"

//Validate user fields like name and password
export const VALIDATE_USER_FIELDS = 'VALIDATE_USER_FIELDS';
export const VALIDATE_USER_FIELDS_SUCCESS = 'VALIDATE_USER_FIELDS_SUCCESS';
export const VALIDATE_USER_FIELDS_FAILURE = 'VALIDATE_USER_FIELDS_FAILURE';
export const RESET_VALIDATE_USER_FIELDS = 'RESET_VALIDATE_USER_FIELDS';

//Get current user(me) from token in localStorage
export const ME_FROM_TOKEN = 'ME_FROM_TOKEN';
export const ME_FROM_TOKEN_SUCCESS = 'ME_FROM_TOKEN_SUCCESS';
export const ME_FROM_TOKEN_FAILURE = 'ME_FROM_TOKEN_FAILURE';
export const RESET_TOKEN = 'RESET_TOKEN';

//Sign Up User
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const RESET_USER = 'RESET_USER';

//Sign In User
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';


//validate email, if success, then load user and login
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAILURE = 'VALIDATE_EMAIL_FAILURE';

//called when email is updated in profile to update main user's email state
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';


//log out user
export const LOGOUT_USER = 'LOGOUT_USER';

// export const ROOT_URL = location.href.indexOf('localhost') > 0 ? 'http://localhost:3000/api' : '/api';